In [1]:
import pandas as pd 
import numpy as np

df=pd.read_csv('/Users/yoon/Desktop/빅데이터 프로그래밍/청약 경쟁률.csv')

for a in range(0,len(df)):
    result=str(df.iloc[a,9]).replace('△','')
    result1=result.replace('(','')
    result2=result1.replace(')','')
    df.iloc[a,9]=float(result2)
df.to_csv('청약 경쟁률.csv', encoding='utf-8-sig')   

           주택관리번호        공고번호  모델번호        주택형 공급세대수  순위  거주코드  거주지역   접수건수  \
0      2020000001  2020000001     1  059.0000H   118   1     1  해당지역  15685   
1      2020000001  2020000001     1  059.0000H   118   1     2  기타지역      0   
2      2020000001  2020000001     1  059.0000H   118   2     1  해당지역      0   
3      2020000001  2020000001     1  059.0000H   118   2     2  기타지역      0   
4      2020000001  2020000001     2  084.0000H   122   1     1  해당지역  18139   
...           ...         ...   ...        ...   ...  ..   ...   ...    ...   
26505  2022000612  2022000612     3  084.9118C    79   2     2  기타지역      1   
26506  2022000612  2022000612     4  114.9688     40   1     1  해당지역      8   
26507  2022000612  2022000612     4  114.9688     40   1     2  기타지역      1   
26508  2022000612  2022000612     4  114.9688     40   2     1  해당지역      6   
26509  2022000612  2022000612     4  114.9688     40   2     2  기타지역      4   

          경쟁률  최저당첨가점  최고당첨가점  평균당첨가점  
0      132.

          주택관리번호        공고번호                  주택명  주택구분코드 주택구분코드명  주택상세구분코드  \
0     2020000001  2020000001          SH 마곡지구 9단지       1     APT         3   
1     2020000004  2020000004        대구연경A-2블록국민임대       1     APT         3   
2     2020000005  2020000005       경북도청신도시 코오롱하늘채       1     APT         3   
3     2020000007  2020000007         학성동 동남하이빌아파트       1     APT         1   
4     2020000008  2020000008  제주첨단과학기술단지A23블록행복주택       1     APT         3   
...          ...         ...                  ...     ...     ...       ...   
1396  2022000601  2022000601              광혜원 포레가       1     APT         1   
1397  2022000602  2022000602       e편한세상 주촌 더프리미어       1     APT         1   
1398  2022000612  2022000612       옥천역 금호어울림 더퍼스트       1     APT         1   
1399  2022000630  2022000630              장성 바울루체       1     APT         1   
1400  2022000640  2022000640       천안 부성지구 우남퍼스트빌       1     APT         1   

     주택상세구분코드명  분양구분코드    분양구분코드명  공급지역코드  ...     

python
python
python
python
pythonli


['It', 'is', 'important', 'to', 'be', 'very', 'pythonly', 'while', 'you', 'are', 'pythoning']
it
is
import
to
be
veri
pythonli
while
you
are
python


['it', 'is', 'import', 'to', 'be', 'veri', 'pythonli', 'while', 'you', 'are', 'python']


['.', 'like', 'swim', 'swimmer']
[[1 1 1 1]]
[[2 0 1 1]]


C:\Users\yoon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_extraction\text.py:516: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
C:\Users\yoon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'afterward', 'alon', 'alreadi', 'alway', 'ani', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becaus', 'becom', 'befor', 'besid', 'cri', 'describ', 'dure', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'formerli', 'forti', 'ha', 'henc', 'hereaft', 'herebi', 'hi', 'howev', 'hundr', 'inde', 'latterli', 'mani', 'meanwhil', 'moreov', 'mostli', 'nobodi', 'noon', 'noth', 'nowher', 'onc', 'onli', 'otherwis', 'ourselv', 'perhap', 'pleas', 'seriou', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'som

정답률 =  0.17188


C:\Users\yoon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


정답률 =  0.7436


[3 3 3]


정답률 =  0.0


150000 [75173 74827]
50000 [24827 25173]


NameError: name 'csv_data' is not defined

ok


      0  1_b  1_c  1_f  1_k  1_s  1_x  2_f  2_g  2_s  ...  21_s  21_v  21_y  \
0     p    0    0    0    0    0    1    0    0    1  ...     1     0     0   
1     e    0    0    0    0    0    1    0    0    1  ...     0     0     0   
2     e    1    0    0    0    0    0    0    0    1  ...     0     0     0   
3     p    0    0    0    0    0    1    0    0    0  ...     1     0     0   
4     e    0    0    0    0    0    1    0    0    1  ...     0     0     0   
...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
8119  e    0    0    0    1    0    0    0    0    1  ...     0     0     0   
8120  e    0    0    0    0    0    1    0    0    1  ...     0     1     0   
8121  e    0    0    1    0    0    0    0    0    1  ...     0     0     0   
8122  p    0    0    0    1    0    0    0    0    0  ...     0     1     0   
8123  e    0    0    0    0    0    1    0    0    1  ...     0     0     0   

      22_d  22_g  22_l  22_m  22_p  22_u  22_w  
0 

Execution time(seconds) 0.39
각 validation 정답률=  [0.68511685 1.         1.         1.         1.         1.
 1.         1.         0.9679803  1.        ]
평균 정답률 :  0.97
